### PR TITLE
New WebTop ActiveSync implementation

### PR DESCRIPTION
**Pull request by gsanchietti**
NethServer/dev#5732

### CODE REVIEW

**Comment by gsanchietti** [comment]
Waiting for new upstream implementation.

**Comment by gsanchietti** [comment]
Currently it seems that mail synchronization doesn't work with `ActiveLegacyIds` set to enabled.
Should we add a note or revert the patch on the mail part?

**Comment by lucagasparini** [comment]
> Currently it seems that mail synchronization doesn't work with `ActiveLegacyIds` set to enabled.
> Should we add a note or revert the patch on the mail part?

It was not possible to determine in which cases mail is not regularly synchronized via EAS.
Even leaving `ActiveLegacyIds` set to enabled in some cases I managed to synchronize the email with EAS.

I suggest leaving pending waiting for all other webtop tests to be completed.

**Comment by lucagasparini** [comment]
> It was not possible to determine in which cases mail is not regularly synchronized via EAS.
> Even leaving `ActiveLegacyIds` set to enabled in some cases I managed to synchronize the email with EAS.

Repeating further tests I can confirm that the emails are regularly synchronized both on Android and on Apple using the new EAS and keeping `ActiveLegacyIds` set to enabled (it was necessary to change the default settings on the device that only synchronized the most recent emails)

**Pull request merged**
