### PR TITLE
small fix in "Configuration backup customization" section

### PR DESCRIPTION
**Pull request by alepolidori**

### CODE REVIEW

**Comment by alepolidori** [comment]
I did the translation on transifex, then pull it on local storage, then commit and then PR.
@DavidePrincipi can't you see the translation on [transifex](https://www.transifex.com/nethserver/docs-v7/viewstrings/#it/backup/107620775) ?

**Comment by DavidePrincipi** [comment]
Yes! It will be merged soon. No need to open PRs for translations hosted on Transifex.com

https://www.transifex.com/nethserver/docs-v7/translate/#it/backup/108574161

**Comment by alepolidori** [comment]
Transifex translations are automatically merged and published ?

**Comment by DavidePrincipi** [comment]
No, they require a manual intervention. Latest package was released on Mon Dec 11 09:01:56. Version 1.2.4

https://github.com/NethServer/nethserver-lang/releases/tag/1.2.4

**Pull request closed without merging**
